### ISSUE TITLE
Cannot find setup/setup_dataset_void.py

### ISSUE THREAD

**Issue by SephirothDaisy** [alexklwong/mondi-python#1]
Thanks for providing such awesome project.
But when I want to try it on my own linux, I cannot fine the corresponding file "setup/setup_dataset_void.py".
Am I missing something?

**Comment by alexklwong** [comment]
Hi, sorry for the inconvenience, looks like we didn't push the setup code for some reason. It's been pushed now in the latest commit:
https://github.com/alexklwong/mondi-python/commit/b4b3f6c8a2b5f64171fb585f50503844930b43e8
