### ISSUE TITLE
Number of valid pixels problem

### ISSUE THREAD

**Issue by KyuminHwang** [alexklwong/mondi-python#6]
When taking void_test_sparse_depth_1500 of the VOID dataset, there are cases where there are less than 1500 sparse points greater than 0. Have you ever checked it?

Even at 150pixel and 500pixel, the number of valid pixels does not satisfy the suggested 150, 500.

Thank you and look forward to your reply.

**Comment by alexklwong** [comment]
Yes that's correct, 1500, 500, 150 are the highest number of points. VOID is a realistic VIO dataset, where the number of tracked points are not guaranteed to be exactly 1500, 500, 150.

**Comment by KyuminHwang** [comment]
Thank you for your quick and kind reply :)
Then I'll close the issue.
